### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by pain8692** [spooldev/SpoolWare#1]
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32api.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pywintypes.py", line 129, in <module>
  File "pywintypes.py", line 44, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\Users\\pain8\\AppData\\Local\\Temp\\_MEI276442\\base_library.zip', 'C:\\Users\\pain8\\AppData\\Local\\Temp\\_MEI276442\\lib-dynload', 'C:\\Users\\pain8\\AppData\\Local\\Temp\\_MEI276442']
I get this error after it attempts to compile and when i try to run the file created in document/dist

**Comment by spooldev** [comment]
Hello there, 

Maybe try removing the following imports from spoolware.py

from win32api import *
from win32gui import *
from win32con import *
from win32file import *

If you get the same error or another, please let me know and I'll be right on it 

Kind regards, 
Spool
